module.exports = [{"opening_id": 1, "tag": "Javascript"},
    {"opening_id": 1, "tag": "Angular.js"},
    {"opening_id": 3, "tag": "Drupal"},
    {"opening_id": 3, "tag": "WordPress"},
    {"opening_id": 3, "tag": "Product Design"},
    {"opening_id": 3, "tag": "Animation"},
    {"opening_id": 14, "tag": "Branding"},
    {"opening_id": 14, "tag": "Graphic Design"},
    {"opening_id": 26, "tag": "Venture Capital"},
    {"opening_id": 26, "tag": "Business Development"},
    {"opening_id": 26, "tag": "Product Management"},
    {"opening_id": 27, "tag": "Communication"},
    {"opening_id": 33, "tag": "3D Printing"},
    {"opening_id": 33, "tag": "3D Modelling"},
    {"opening_id": 33, "tag": "Graphic Design"},
    {"opening_id": 77, "tag": "Social Media Marketing"},
    {"opening_id": 77, "tag": "Google analytics"},
    {"opening_id": 77, "tag": "Growth Hacking"},
    {"opening_id": 78, "tag": "Programming"},
    {"opening_id": 78, "tag": "MongoDB"},
    {"opening_id": 95, "tag": "Programming"},
    {"opening_id": 96, "tag": "React.js"},
    {"opening_id": 117, "tag": "Programming"},
    {"opening_id": 117, "tag": "Web Programming"},
    {"opening_id": 121, "tag": "Javascript"},
    {"opening_id": 132, "tag": "Javascript"},
    {"opening_id": 132, "tag": "Web Hosting"},
    {"opening_id": 132, "tag": "GitHub"},
    {"opening_id": 132, "tag": "Project Management"},
    {"opening_id": 135, "tag": "Crowdfunding"},
    {"opening_id": 138, "tag": "Industrial Design"},
    {"opening_id": 138, "tag": "Entrepreneurship"},
    {"opening_id": 152, "tag": "Programming"},
    {"opening_id": 153, "tag": "Adobe Photoshop"},
    {"opening_id": 153, "tag": "3D Design"},
    {"opening_id": 154, "tag": "Javascript"},
    {"opening_id": 154, "tag": "Angular.js"},
    {"opening_id": 154, "tag": "Node.js"},
    {"opening_id": 155, "tag": "Business Angels"},
    {"opening_id": 155, "tag": "Fundraising"},
    {"opening_id": 164, "tag": "Programming"},
    {"opening_id": 164, "tag": "Graphic Design"},
    {"opening_id": 164, "tag": "Adobe Photoshop"},
    {"opening_id": 168, "tag": "Graphic Design"},
    {"opening_id": 168, "tag": "Programming"},
    {"opening_id": 178, "tag": "Programming"},
    {"opening_id": 189, "tag": "Artificial Intelligence"},
    {"opening_id": 189, "tag": "SEO"},
    {"opening_id": 189, "tag": "Analytics"},
    {"opening_id": 190, "tag": "Social Media Marketing"},
    {"opening_id": 190, "tag": "Public Relations"},
    {"opening_id": 190, "tag": "Ecommerce"},
    {"opening_id": 190, "tag": "Fashion"},
    {"opening_id": 204, "tag": "Branding"},
    {"opening_id": 207, "tag": "Photography"},
    {"opening_id": 207, "tag": "Graphic Design"},
    {"opening_id": 207, "tag": "Illustration"},
    {"opening_id": 208, "tag": "Venture Capital"},
    {"opening_id": 208, "tag": "Venture Financing"},
    {"opening_id": 208, "tag": "Business"},
    {"opening_id": 209, "tag": "Venture Capital"},
    {"opening_id": 209, "tag": "Venture Financing"},
    {"opening_id": 210, "tag": "SEO"},
    {"opening_id": 222, "tag": "Python"},
    {"opening_id": 224, "tag": "Manufacturing Design"},
    {"opening_id": 225, "tag": "Manufacturing Design"},
    {"opening_id": 234, "tag": "Javascript"},
    {"opening_id": 242, "tag": "Mobile Advertising"},
    {"opening_id": 242, "tag": "SEO"},
    {"opening_id": 242, "tag": "App Store"},
    {"opening_id": 242, "tag": "Marketing Strategy"},
    {"opening_id": 243, "tag": "iOS"},
    {"opening_id": 243, "tag": "Android"},
    {"opening_id": 243, "tag": "Graphic Design"},
    {"opening_id": 244, "tag": "Script Writing"},
    {"opening_id": 262, "tag": "Computer Graphics"},
    {"opening_id": 277, "tag": "Javascript"},
    {"opening_id": 277, "tag": "Product Design"},
    {"opening_id": 279, "tag": "Javascript"},
    {"opening_id": 279, "tag": " php"}]
