module.exports = [
  { name: 'joint ventures', categories: [1] },
  { name: 'Icon Design', categories: [4, 2] },
  { name: 'urban design', categories: [4] },
  { name: 'Digital Signal Processing', categories: [5] },
  { name: 'service client', categories: [1] },
  { name: 'Security Engineering', categories: [7, 5] },
  { name: 'analysis', categories: [1, 9, 5] },
  { name: 'Structural Engineering', categories: [5] },
  { name: 'English Spelling', categories: [8, 14] },
  { name: 'sculpture', categories: [2, 4] },
  { name: 'Lyric Writing', categories: [8, 14] },
  { name: 'FileMaker', categories: [3, 7] },
  { name: 'Adobe CS', categories: [2, 4, 12] },
  { name: 'Screenwriting', categories: [2, 8, 14] },
  { name: 'pro active leader', categories: [''] },
  { name: 'Artlantis Studio', categories: [2, 4] },
  { name: 'Clojure', categories: [7, 12, 15] },
  { name: 'matlab', categories: [7] },
  { name: 'Neo4j', categories: [3, 7] },
  { name: 'ipo', categories: [1] },
  { name: 'Maya', categories: [7, 4] },
  { name: 'system architecture', categories: [7] },
  {
    name: 'Oracle Financials Applications',
    categories: [7, 1, 15]
  },
  { name: 'start up', categories: [1, 2] },
  { name: 'Raster Graphics Editor', categories: [4, 12, 13] },
  { name: 'Prototype Javascript Framework', categories: [13] },
  { name: 'theatre', categories: [14, 2] },
  { name: 'Fiber Optics', categories: [5] },
  { name: 'budgets', categories: [1, 9] },
  { name: 'automation', categories: [5] },
  { name: 'AccountMate', categories: [1, 15] },
  { name: 'Cognos', categories: [1, 15] },
  { name: 'Transaction Processing', categories: [7] },
  { name: 'international business', categories: [1, 9] },
  { name: 'Hungarian', categories: [8, 14] },
  { name: 'account relationship building', categories: [1, 9] },
  { name: 'Technical Writing', categories: [14] },
  { name: 'company set up', categories: [1] },
  { name: 'Brochure Design', categories: [4, 2] },
  { name: 'education', categories: [16] },
  { name: 'corporate tax', categories: [1, 9] },
  { name: '3D Systems', categories: [5, 6] },
  { name: 'asset managment', categories: [1] },
  { name: 'Building Information Modeling', categories: [7, 5] },
  { name: 'ip', categories: [1, 5] },
  { name: 'policy analysis', categories: [1] },
  { name: 'Electrical Manufacture', categories: [5] },
  { name: 'mac os x server', categories: [15] },
  { name: 'product launch', categories: [1] },
  { name: 'Article Rewriting', categories: [14] },
  { name: 'pay per click ppc', categories: [9] },
  { name: 'mobile technology', categories: [10] },
  { name: 'Textile Engineering', categories: [5] },
  { name: 'online community management', categories: [9] },
  { name: 'http', categories: [13, 7] },
  { name: 'XHTML', categories: [13, 7] },
  { name: 'FTP', categories: [13, 7] },
  { name: '.NET for Web', categories: [13, 7] },
  { name: 'gambling', categories: [6] },
  { name: 'Adobe Dreamweaver CS', categories: [15] },
  { name: 'Short Stories', categories: [14, 2] },
  { name: 'face to face presentations', categories: [2, 9] },
  { name: 'JSON', categories: [13] },
  { name: 'computer science', categories: [7, 11, 5] },
  { name: 'Covers & Packaging', categories: [9] },
  { name: 'k 12 education', categories: [16] },
  { name: 'mutual funds', categories: [1] },
  { name: 'Microsoft Publisher', categories: [15] },
  { name: 'vo ip', categories: [11, 13, 15] },
  { name: 'maple', categories: [15] },
  { name: 'os x', categories: [15] },
  { name: 'performing arts', categories: [2] },
  { name: 'Voice Over', categories: [15] },
  { name: 'Catalan', categories: [8] },
  { name: 'i os development', categories: [11] },
  { name: 'Accounts Receivable', categories: [1] },
  { name: 'database admin', categories: [3] },
  { name: 'Data Protection', categories: [3] },
  { name: 'digital media', categories: [9] },
  { name: 'Google App Engine', categories: [15] },
  {
    name: 'key account acquisition retention',
    categories: [1, 9]
  },
  { name: 'japanese culture', categories: [8] },
  { name: 'tax advisory', categories: [1] },
  { name: 'networking', categories: [1] },
  { name: 'collective funds', categories: [1] },
  { name: 'CAM', categories: [5] },
  { name: 'Poster Design', categories: [4, 2] },
  { name: 'tcp ip', categories: [13, 7] },
  { name: 'Predictive Analytics', categories: [1, 9] },
  { name: 'contract management', categories: [1] },
  { name: 'Vector Graphics Editor', categories: [15, 4] },
  { name: 'html 5', categories: [12, 13] },
  { name: 'accent reduction', categories: [8] },
  { name: 'Kaizen', categories: [1, 16] },
  { name: 'Vulnerability Assessment', categories: [7] },
  { name: 'Delphi', categories: [15] },
  { name: 'flask', categories: [13] },
  { name: 'Job Costing', categories: [5, 1] },
  { name: 'XSLT', categories: [13, 7] },
  { name: 'ADO.NET', categories: [13, 7] },
  { name: 'mobile internet', categories: [10] },
  { name: 'Software Documentation', categories: [11, 15] },
  { name: 'Audio Engineering', categories: [5, 16] },
  { name: 'LinkedIn Development', categories: [9] },
  { name: 'ColdFusion', categories: [15, 13] },
  { name: 'west africa', categories: [16] },
  { name: 'agile methodologies', categories: [11, 13, 1] },
  { name: 'Microsoft Visio', categories: [15] },
  { name: 'data center', categories: [3] },
  { name: 'Perl', categories: [7, 11, 15] },
  { name: 'microsoft access', categories: [15] },
  { name: 'Computer-Aided Design', categories: [4] },
  { name: 'Sony Vegas', categories: [15] },
  { name: 'improvisation', categories: [16] },
  { name: 'Geospatial', categories: [16] },
  { name: 'Nanotechnology', categories: [5] },
  { name: 'vas', categories: [15] },
  { name: 'international marketing', categories: [9] },
  { name: 'Data Storage', categories: [3] },
  { name: 'Email Etiquette', categories: [9] },
  { name: 'volunteer management', categories: [1] },
  { name: 'WinJS', categories: [12, 13] },
  { name: 'Typing', categories: [14] },
  { name: 'Payroll', categories: [15, 1] },
  { name: 'Apache Kafka', categories: [15] },
  { name: 'b2b', categories: [1] },
  { name: 'User Guides', categories: [15] },
  { name: 'strategic marketing', categories: [9] },
  { name: 'Environmental Law', categories: [16] },
  { name: 'Cinema D', categories: [2] },
  { name: 'tax structuring', categories: [1, 15] },
  { name: 'ANSYS', categories: [15] },
  { name: 'security', categories: [7] },
  { name: 'financial markets', categories: [1] },
  { name: 'Prezi', categories: [15] },
  { name: 'solution selling', categories: [9] },
  { name: 'imagination', categories: [16] },
  { name: 'redis', categories: [3, 7] },
  { name: 'listening to customers', categories: [9] },
  { name: 'Book Writing', categories: [14] },
  { name: 'Regulation', categories: [16] },
  { name: 'technology evangelist', categories: [16] },
  { name: 'Personal Assistant', categories: [16] },
  { name: 'online marketing', categories: [9] },
  { name: 'Online Writing', categories: [14] },
  { name: 'Geographic Information Systems', categories: [7] },
  { name: 'contract negotiation', categories: [1] },
  { name: 'Autodesk Maya', categories: [6, 15] },
  { name: 'express js', categories: [12, 13] },
  { name: 'Compiler', categories: [15] },
  { name: 'pharmaceutical', categories: [16] },
  { name: 'Trademark', categories: [16] },
  { name: 'investment strategies', categories: [1] },
  { name: 'net', categories: [13] },
  { name: 'Eloqua', categories: [15] },
  { name: 'cohort analysis', categories: [9] },
  { name: 'partner management', categories: [1] },
  { name: 'teaching', categories: [16] },
  { name: 'business planning', categories: [1] },
  { name: "Children's Writing", categories: [14] },
  { name: 'Stratasys', categories: [15] },
  { name: 'hootsuite', categories: [15] },
  { name: 'English Punctuation', categories: [14, 8] },
  { name: 'marketing event planning', categories: [9] },
  { name: 'Inventory Management', categories: [9] },
  { name: 'Virtual Assistant', categories: [4] },
  { name: 'television', categories: [16] },
  {
    name: 'customer relationship management crm',
    categories: ['']
  },
  { name: 'Word Processing', categories: [15] },
  {
    name: 'CISSP Certified Information Systems Security Professional',
    categories: [15, 7]
  },
  { name: 'web applications', categories: [13] },
  { name: 'Immigration Law', categories: [16] },
  { name: 'cross border transactions', categories: [1, 9] },
  { name: 'equity capital markets', categories: [1] },
  { name: 'Oracle E-Business Suite', categories: [15] },
  { name: 'PSD to HTML', categories: [13] },
  { name: 'process improvement', categories: [7] },
  { name: 'user interface', categories: [12, 13] },
  { name: 'Testopia', categories: [15] },
  { name: 'Croatian', categories: [8] },
  { name: 'Data Logistics', categories: [3] },
  { name: 'tweet deck', categories: [9] },
  { name: 'Greek', categories: [8] },
  { name: 'community management', categories: [9] },
  { name: 'Portuguese', categories: [8] },
  { name: 'business relationship management', categories: [1] },
  { name: 'Adobe LiveCycle Designer', categories: [15] },
  { name: 'Swedish', categories: [8] },
  { name: 'Content Management System', categories: [7] },
  { name: 'Natural Language Processing', categories: [8, 7] },
  { name: 'transfer pricing', categories: [1] },
  { name: 'administrative organization', categories: [16] },
  { name: 'Broadcast Engineering', categories: [5] },
  { name: 'Polymer', categories: [5] },
  { name: 'urban economics', categories: [1] },
  { name: 'firewalls', categories: [7] },
  { name: 'Academic Writing', categories: [14] },
  { name: 'mobile product development', categories: [10] },
  { name: 'Bookkeeping', categories: [1] },
  { name: 'Sybase Programming', categories: [15, 11] },
  { name: 'D3.js', categories: [12, 13] },
  { name: 'online research', categories: [9] },
  { name: 'Virtualization', categories: [6, 11] },
  { name: 'Feature Writing', categories: [14] },
  { name: 'Database Administration', categories: [3] },
  { name: 'swift', categories: [11, 15, 15] },
  { name: 'FourSquare Development', categories: [15] },
  { name: 'open source', categories: [7, 11] },
  { name: 'Adobe Dreamweaver', categories: [15] },
  { name: 'algorithms', categories: [5, 11, 7] },
  { name: 'Cover Design', categories: [4, 2] },
  { name: 'Mobile Operating System', categories: [10, 7] },
  { name: 'Astrophysics', categories: [16] },
  { name: 'business objects', categories: [7] },
  { name: 'Climate Sciences', categories: [16] },
  { name: 'Sencha Architect', categories: [13, 16] },
  { name: 'channel partners', categories: [1, 5] },
  { name: 'In-Game Advertising', categories: [9, 6] },
  { name: 'google apps', categories: [15] },
  { name: 'SAS Business Analytics', categories: [1] },
  { name: 'Accounts Payable', categories: [1] },
  { name: 'Twig', categories: [13] },
  { name: 'community outreach', categories: [9] },
  { name: 'digital strategy', categories: [1, 9] },
  { name: 'Telugu', categories: [8] },
  { name: 'Copyright', categories: [1, 16] },
  { name: 'Manual Test Execution', categories: [5] },
  { name: 'portfolio management', categories: [1] },
  { name: 'Privacy', categories: [15, 16, 7] },
  { name: 'indirect taxation', categories: [1] },
  { name: 'competitive intelligence', categories: [1] },
  { name: 'CAD/CAM/CAE', categories: [7, 11, 15] },
  { name: 'demand generation', categories: [9] },
  { name: 'infrastructure', categories: [7] },
  { name: 'open gl', categories: [4, 15, 6] },
  { name: 'System Analysis', categories: [7] },
  { name: 'USB Electronics', categories: [5] },
  { name: 'Debugging', categories: [7, 15] },
  { name: 'affinity', categories: [2, 7] },
  { name: 'Full-text Search Engines', categories: [1] },
  { name: 'ActionScript', categories: [13] },
  { name: 'Adobe FrameMaker', categories: [15] },
  { name: 'Simplified Chinese', categories: [8] },
  { name: 'Application Server', categories: [7] },
  { name: 'Learning Management System', categories: [7] },
  { name: 'Modeling Language', categories: [7] },
  { name: 'data visualization', categories: [3] },
  { name: 'network architecture', categories: [7] },
  { name: 'Oracle Transportation Management', categories: [15] },
  { name: 'motion design', categories: [4, 5] },
  { name: 'dialects', categories: [8] },
  { name: 'communication marketing', categories: [9] },
  { name: 'Mechatronics', categories: [5] },
  { name: 'team leadership', categories: [1] },
  { name: 'slideshare', categories: [9] },
  { name: 'Underscore.js', categories: [13] },
  { name: 'photoshop', categories: [15] },
  { name: 'Embedded System', categories: [7] },
  { name: '3Ds Max', categories: [16] },
  { name: 'Apache', categories: [7] },
  { name: 'key account development', categories: [1] },
  { name: 'cross cultural management', categories: [16] },
  { name: 'Cartoon', categories: [2, 4] },
  { name: 'Records Management', categories: [16] },
  { name: 'legal advice', categories: [16] },
  { name: 'financial services', categories: [1] },
  { name: 'commercial management', categories: [1, 9] },
  { name: 'promotions', categories: [9] },
  { name: 'Data Entry System', categories: [3] },
  { name: 'Administrative Research', categories: [16] },
  { name: 'Adobe Flex', categories: [15] },
  { name: 'MySpace Development', categories: [16] },
  { name: 'GIMP', categories: [15] },
  { name: 'yoruba', categories: [15] },
  { name: 'Network Monitoring', categories: [7] },
  { name: 'investments', categories: [1] },
  { name: 'AutoDesk Revit', categories: [15] },
  { name: 'public policy', categories: [16] },
  { name: 'Construction Monitoring', categories: [16] },
  { name: 'R-Hadoop', categories: [15] },
  { name: 'playwriting', categories: [14, 2] },
  { name: 'SQLite Programming', categories: [7] },
  { name: 'database management', categories: [3] },
  { name: 'VB.NET', categories: [11] },
  { name: 'in design', categories: [4, 12] },
  { name: 'Wix', categories: [13] },
  { name: 'LaTeX', categories: [14] },
  { name: 'Ext GWT', categories: [13] },
  { name: 'web marketing', categories: [9] },
  { name: 'Google Web Toolkit', categories: [13, 15] },
  { name: 'Commercials', categories: [9] },
  { name: 'ArchiCAD', categories: [15] },
  { name: 'Oracle Agile', categories: [7, 15, 1] },
  { name: 'innovation', categories: [1] },
  { name: 'Circuit Design', categories: [5] },
  { name: 'v mware', categories: [7, 15] },
  { name: 'customer satisfaction', categories: [1] },
  { name: 'open cl', categories: [11] },
  { name: 'speech', categories: [1] },
  { name: 'Software framework', categories: [11] },
  { name: 'amazon ec 2', categories: [7] },
  { name: 'Creative writing', categories: [14] },
  { name: 'Web Components', categories: [13] },
  { name: 'social software', categories: [11] },
  { name: '3D Animation', categories: [2, 6] },
  { name: 'Poetry', categories: [2, 16] },
  { name: 'Geolocation', categories: [13, 10, 11] },
  { name: 'relation build', categories: [''] },
  { name: 'Sports Writing', categories: [14] },
  {
    name: 'Integrated Development Environment',
    categories: [7]
  },
  { name: 'Banner Ads', categories: [9] },
  { name: 'objective c', categories: [10] },
  { name: 'Litigation', categories: [1] },
  { name: 'international development', categories: [1] },
  { name: 'PL/SQL', categories: [3] },
  { name: 'Statistical Computing', categories: [7] },
  { name: 'Virtual Machine', categories: [11] },
  { name: 'Joomla!', categories: [9] },
  { name: 'Scientific Computation', categories: [5, 6] },
  { name: 'Technical Support', categories: [5] },
  { name: 'private equity', categories: [1] },
  { name: 'Fiction Writing', categories: [14, 2] },
  { name: 'Hadoop', categories: [7] },
  { name: 'Network Analysis', categories: [7] },
  { name: 'QA Engineering', categories: [5] },
  { name: 'SPSS', categories: [1] },
  { name: 'Sewing', categories: [2] },
  { name: 'Japanese', categories: [8] },
  { name: 'Business Card Design', categories: [4] },
  {
    name: 'Microsoft Access Administration',
    categories: [1, 9]
  },
  { name: 'Label & Package Design', categories: [4] },
  { name: 'Reverse Engineering', categories: [5, 1] },
  { name: 'startup consulting', categories: [1] },
  { name: 'System Programming', categories: [11] },
  { name: 'Non-Fiction Writing', categories: [14] },
  { name: 'Autodesk Inventor', categories: [15] },
  { name: 'Adobe Analytics', categories: [1, 4, 15] },
  { name: 'English Grammar', categories: [8] },
  { name: 'Hospitality', categories: [1] },
  { name: 'Adobe Acrobat', categories: [1, 4, 15] },
  { name: 'Resume Writing', categories: [14] },
  { name: 'Java ME', categories: [13] },
  { name: 'fixed income', categories: [1] },
  { name: 'Landscape Design', categories: [2, 16] },
  { name: 'Bulk Marketing', categories: [9] },
  { name: 'Website Analytics', categories: [13, 9] },
  { name: 'Data Ingestion', categories: [3] },
  { name: 'Web Application Framework', categories: [13] },
  { name: 'Speech Writing', categories: [14] },
  { name: 'Network Programming', categories: [7] },
  { name: 'Web Publishing', categories: [14, 9] },
  { name: 'Graph Databases', categories: [3] },
  { name: 'pre sales', categories: [9, 1] },
  { name: 'team building', categories: [1] },
  { name: 'Salesforce.com Development', categories: [9, 15] },
  { name: 'facebook', categories: [9, 1] },
  { name: 'Eclipse', categories: [''] },
  { name: 'Bitcoin', categories: [1] },
  { name: 'mongo db', categories: [3] },
  { name: 'financial modeling', categories: [1] },
  { name: 'management consulting', categories: [1] },
  { name: '3D Scanning', categories: [5] },
  { name: 'Networking & Information Systems', categories: [7] },
  { name: 'Regression Testing', categories: [5] },
  { name: 'Petroleum Engineering', categories: [5] },
  { name: 'Communication', categories: [1] },
  { name: 'Xcode', categories: [11] },
  { name: 'Script Writing', categories: [11] },
  { name: 'Gulp.js', categories: [13] },
  { name: 'investment management', categories: [1] },
  { name: 'go to market strategy', categories: [1] },
  { name: 'Oracle Hyperion', categories: [15] },
  { name: 'change management', categories: [1] },
  { name: 'Cartography & Maps', categories: [16] },
  { name: 'Web Server', categories: [7] },
  { name: 'sales management', categories: [1] },
  { name: 'iPhone SDK', categories: [10] },
  { name: 'Fashion Modeling', categories: [2] },
  { name: 'microsoft power point', categories: [1, 15] },
  { name: 'REST', categories: [13, 10] },
  { name: 'mobile marketing', categories: [9] },
  { name: 'Financial Writing', categories: [14, 1] },
  { name: 'ITIL', categories: [7] },
  { name: 'Newsletters', categories: [9] },
  { name: 'social business', categories: [1] },
  { name: 'Audio Editing', categories: [2] },
  { name: 'CodeIgniter', categories: [13] },
  { name: 'Microsoft Sharepoint', categories: [15] },
  { name: 'Geographic Information Systems', categories: [7] },
  { name: 'Scalable analytics', categories: [7] },
  { name: 'SketchUp Pro', categories: [4, 15] },
  { name: 'Microsoft Access Programming', categories: [1, 15] },
  { name: 'Final Cut Pro X', categories: [2, 15] },
  { name: 'Analog Electronics', categories: [5] },
  { name: 'Landing Pages', categories: [12, 2] },
  { name: 'CATIA', categories: [5, 15] },
  { name: 'Prestashop', categories: [9] },
  { name: 'microsoft windows', categories: [1, 15] },
  { name: 'YouTube Development', categories: [13] },
  { name: 'ASP.NET MVC', categories: [13] },
  { name: 'integration', categories: [12] },
  { name: 'Sound Design', categories: [2] },
  { name: 'Personal Development', categories: [1] },
  { name: 'CakePHP', categories: [13] },
  { name: 'Microsoft Visual Studio', categories: [2, 15] },
  { name: 'Lightwave 3D', categories: [5, 15] },
  { name: 'Data Interchange', categories: [3] },
  { name: 'Drupal', categories: [9] },
  { name: 'Typography', categories: [2, 12] },
  { name: 'Grunt.js', categories: [13] },
  { name: 'Clean Technology', categories: [5] },
  { name: 'eBooks', categories: [16] },
  { name: 'Press Releases', categories: [1] },
  { name: 'Infographics', categories: [4] },
  { name: 'PostgreSQL Administration', categories: [3] },
  { name: 'Enterprise Resource Planning', categories: [1] },
  { name: 'Visual Basic', categories: [11] },
  { name: 'Database Programming', categories: [3] },
  { name: 'Oracle PL/SQL', categories: [3, 15] },
  { name: 'Genetic Engineering', categories: [5] },
  { name: 'Scala', categories: [11] },
  { name: 'Twitter Development', categories: [13, 10] },
  { name: 'nonprofits', categories: [1] },
  { name: 'Web Services Development', categories: [13] },
  { name: 'due diligence', categories: [1] },
  { name: 'Adaptive Algorithms', categories: [5, 11, 7] },
  { name: 'Socket.io', categories: [13, 10] },
  { name: 'Wireless', categories: [5] },
  { name: 'Digital Painting', categories: [2] },
  { name: 'Network Engineering', categories: [7] },
  { name: 'SQL Programming', categories: [3] },
  { name: 'Korean', categories: [8] },
  { name: 'Google Maps', categories: [15] },
  {
    name: 'Microsoft SQL Server Programming',
    categories: [7, 15]
  },
  { name: 'Pinterest Marketing', categories: [9] },
  { name: 'Test Automation', categories: [11, 7] },
  { name: 'Financial Communication', categories: [1] },
  { name: '3D', categories: [5, 4] },
  { name: 'Backbone.js', categories: [13, 10] },
  { name: 'Mac OSX', categories: [11, 7] },
  { name: 'Licensing', categories: [1] },
  { name: 'Technical Writing', categories: [14] },
  { name: 'Imaging', categories: [5, 15] },
  { name: 'Stata', categories: [15] },
  { name: 'Data Warehousing', categories: [7, 3] },
  { name: 'Sales Writing', categories: [14] },
  { name: 'enterprise software', categories: [1] },
  { name: 'Sage 50 Accounting', categories: [1] },
  { name: 'telecommunications', categories: [5, 7] },
  { name: 'mobile applications', categories: [10] },
  { name: 'Medical Writing', categories: [14] },
  { name: 'Network Administration', categories: [7] },
  { name: 'Voice Acting', categories: [2] },
  { name: 'Compliance', categories: [1] },
  { name: 'Android SDK', categories: [10] },
  { name: 'NoSQL', categories: [3] },
  { name: 'Google AdSense', categories: [9, 15] },
  { name: 'Network Design', categories: [7, 11] },
  { name: 'Autodesk', categories: [9, 15] },
  { name: 'SketchUp', categories: [4, 15] },
  { name: 'QA Testing', categories: [1, 14] },
  { name: 'Proposal Writing', categories: [14] },
  { name: 'Google Go', categories: [10] },
  { name: 'Travel Writing', categories: [1] },
  { name: 'competitive analysis', categories: [1] },
  { name: 'Norwegian', categories: [8] },
  { name: 'Legal Research', categories: [1] },
  { name: 'Motion Graphics', categories: [6, 4] },
  { name: 'eBay', categories: [9, 16] },
  { name: 'MailChimp', categories: [9, 1, 15] },
  { name: 'Operating Systems', categories: [7, 11] },
  { name: 'business intelligence', categories: [1, 15] },
  { name: 'Core Java', categories: [11] },
  { name: 'Data Structures', categories: [3] },
  { name: 'strategic partnerships', categories: [1] },
  { name: 'Embedded Systems', categories: [7] },
  { name: 'Manufacturing Design', categories: [5, 4] },
  { name: 'user experience', categories: [4, 12] },
  { name: 'Test automation framework', categories: [13, 11] },
  { name: 'mergers acquisitions', categories: [1] },
  { name: 'data analysis', categories: [1] },
  { name: 'Mobile Development Framework', categories: [10] },
  { name: 'SAP', categories: [9] },
  { name: 'Business writing', categories: [1, 15] },
  { name: 'Computer Skills', categories: [11, 13] },
  { name: 'Contracts', categories: [1] },
  { name: 'Patent Law', categories: [1] },
  { name: 'Communications', categories: [1] },
  { name: 'Application Lifecycle Management', categories: [1] },
  { name: 'Audio Design', categories: [2, 4] },
  { name: 'new business development', categories: [1] },
  { name: 'Data Entry', categories: [1] },
  { name: 'Time Management', categories: [1] },
  { name: 'power point', categories: [1, 15] },
  { name: 'Chemical Engineering', categories: [5] },
  { name: 'Digital Electronics', categories: [5] },
  { name: 'Rails', categories: [13] },
  { name: 'Security & Control', categories: [7] },
  { name: 'Facebook Development', categories: [13, 10] },
  { name: 'Engineering Design', categories: [5, 4] },
  { name: 'Print Advertising', categories: [9, 4] },
  { name: 'Internet Security', categories: [7] },
  { name: 'Magento', categories: [9, 15] },
  { name: 'Bing Ads', categories: [9] },
  { name: 'Telecommunications Engineering', categories: [5] },
  { name: '.NET', categories: [11, 13] },
  { name: 'Spring', categories: [15] },
  { name: 'Editing', categories: [2] },
  { name: 'Adobe Photoshop CS', categories: [4, 12, 15] },
  { name: 'Building Architecture', categories: [16] },
  { name: 'PostgreSQL Programming', categories: [3] },
  { name: 'Electronic Design', categories: [5, 4] },
  { name: 'team management', categories: [1] },
  { name: 'XML', categories: [11] },
  { name: 'Objective-C', categories: [11] },
  { name: 'Presentation Design', categories: [4] },
  { name: 'mobile devices', categories: [10, 5] },
  { name: 'electronic systems', categories: [5] },
  { name: 'TCP/IP', categories: [13] },
  { name: 'Wearables Technology', categories: [7, 5] },
  { name: 'Chinese', categories: [8] },
  { name: 'Data Interpretation', categories: [1] },
  { name: 'Insurance', categories: [1] },
  { name: 'Computational science', categories: [11, 16] },
  { name: 'Final Cut Pro', categories: [1, 15] },
  { name: 'Object Oriented PHP', categories: [12] },
  { name: 'Microsoft Outlook', categories: [1, 15] },
  { name: 'growth strategies', categories: [9] },
  { name: 'Loyalty Marketing', categories: [9, 1] },
  { name: 'OpenGL', categories: [5, 4] },
  { name: 'product development', categories: [1] },
  { name: 'AJAX', categories: [13] },
  { name: 'Legal Writing', categories: [14, 1] },
  { name: 'App Store', categories: [10] },
  { name: 'JIRA', categories: [11] },
  { name: 'Civil Engineering', categories: [5] },
  { name: 'Application Development', categories: [11] },
  { name: '3D Technology', categories: [5, 4] },
  { name: 'Data Cleansing', categories: [7, 3] },
  { name: 'product marketing', categories: [9, 1] },
  { name: 'Acquisitions', categories: [1] },
  { name: 'Email', categories: [1, 15] },
  { name: 'Windows', categories: [1, 15] },
  { name: 'English Proofreading', categories: [14, 8] },
  { name: 'API', categories: [13, 11, 10] },
  { name: 'Tax', categories: [1] },
  { name: 'Video Publishing', categories: [2] },
  { name: 'Adobe InDesign CS', categories: [4, 12, 15] },
  { name: 'Computer Architecture', categories: [7] },
  { name: 'Network Security', categories: [7] },
  { name: 'e commerce', categories: [1, 9] },
  { name: 'Industrial Design', categories: [4, 2] },
  { name: 'Wireframes', categories: [13, 4] },
  { name: 'Arduino', categories: [5, 11] },
  { name: 'Visual Arts', categories: [2] },
  { name: 'Data Mining', categories: [7, 3] },
  { name: 'Internet Research', categories: [1] },
  { name: 'IT', categories: [7] },
  { name: 'AutoCAD', categories: [5, 4, 17] },
  { name: 'Sketching', categories: [2, 4] },
  { name: 'Proofreading', categories: [14] },
  { name: 'Real Estate Law', categories: [1] },
  { name: 'Legal Consulting', categories: [1] },
  { name: 'Electronics', categories: [5] },
  { name: 'Docker', categories: [13, 11, 15] },
  { name: 'Information Management', categories: [1, 7] },
  { name: 'Drawing', categories: [2] },
  { name: 'Biology', categories: [16] },
  { name: 'Crowdfunding', categories: [1] },
  { name: 'Art Direction', categories: [2] },
  { name: 'Mobile App Testing', categories: [10] },
  { name: 'Amazon Web Services', categories: [7, 15] },
  { name: 'Mechanical Design', categories: [4, 5] },
  { name: 'Travel Planning', categories: [1] },
  { name: 'Adobe Premiere', categories: [2, 15] },
  { name: 'Office Management', categories: [1] },
  { name: 'Adobe After Effects', categories: [2, 15] },
  { name: 'Web Content', categories: [14, 9] },
  { name: 'Business Mathematics', categories: [1, 16] },
  { name: 'Social Media Optimization SMO', categories: [9] },
  { name: 'Writing', categories: [1] },
  { name: 'social media', categories: [9] },
  { name: 'Media Relations', categories: [1] },
  { name: '3D Rendering', categories: [4, 5, 15] },
  { name: 'Translation', categories: [14, 8] },
  { name: 'C', categories: [11] },
  { name: 'Broadcast Advertising', categories: [9] },
  { name: 'Electronic Engineering', categories: [5] },
  { name: 'Copy Editing', categories: [14] },
  { name: 'Display Ads', categories: [9] },
  { name: 'Software Engineering', categories: [11] },
  { name: 'Business Process Outsourcing', categories: [1] },
  { name: 'Legal', categories: [1] },
  { name: 'Recruitment', categories: [1] },
  { name: 'MySQL Administration', categories: [3] },
  { name: 'Videography', categories: [2] },
  { name: '3D Design', categories: [5, 4, 6] },
  { name: 'business strategy', categories: [1] },
  { name: 'Interior Design', categories: [4, 16] },
  { name: 'Journalism', categories: [16] },
  { name: 'Human Sciences', categories: [16] },
  { name: 'SolidWorks', categories: [5, 15] },
  { name: 'Pitching', categories: [1] },
  { name: 'Rhinoceros 3D', categories: [6, 15, 5] },
  { name: 'Haskell', categories: [11] },
  { name: 'Relational Databases', categories: [3] },
  { name: 'Editorial Writing', categories: [14] },
  { name: 'Viral Marketing', categories: [9] },
  { name: 'Commercial', categories: [9] },
  { name: 'Asset Management', categories: [1] },
  { name: 'Materials Engineering', categories: [5] },
  { name: 'Business Writing', categories: [14] },
  { name: 'Web Development', categories: [13] },
  { name: 'ecommerce solutions', categories: [9] },
  { name: 'Mobile Advertising', categories: [9] },
  { name: 'Social Networks Building', categories: [13, 9] },
  { name: 'Salesforce.com', categories: [9, 15] },
  { name: 'Django', categories: [13] },
  { name: 'Adobe Illustrator CS', categories: [4, 2, 15] },
  { name: 'Community', categories: [9] },
  { name: 'ScrumWorks', categories: [11] },
  { name: 'Web Programming', categories: [13] },
  { name: 'Bootstrap', categories: [1, 12, 13] },
  { name: 'Adobe Photoshop Lightroom', categories: [2, 15] },
  { name: 'Blog Writing', categories: [14] },
  { name: 'R', categories: [11, 5] },
  { name: 'Unix', categories: [7] },
  { name: 'Express.js', categories: [13, 10] },
  { name: 'Tax Law', categories: [1] },
  { name: 'Creative Writing', categories: [14] },
  { name: 'Software Testing', categories: [11] },
  { name: 'Investment Research', categories: [1] },
  { name: 'Valuation', categories: [1] },
  { name: 'Arts & Crafts', categories: [2] },
  { name: 'Content Writing', categories: [14] },
  { name: 'Lead Generation', categories: [9, 1] },
  { name: 'Web Content Management', categories: [14] },
  { name: 'Game Programming', categories: [6] },
  { name: 'Architecture', categories: [16] },
  { name: 'Physics', categories: [16] },
  { name: 'Intellectual Property', categories: [1] },
  { name: 'Logistics & Shipping', categories: [1] },
  { name: 'Adobe Creative Suite', categories: [12, 15, 4] },
  { name: 'Fashion', categories: [2, 4, 16] },
  { name: 'Data Modeling', categories: [7, 3] },
  { name: 'Italian', categories: [8] },
  { name: '3D Modelling', categories: [5] },
  { name: 'Ad planning & buying', categories: [9] },
  { name: 'Java EE', categories: [11, 15] },
  { name: 'Copywriting', categories: [1] },
  { name: 'Civil Law', categories: [1] },
  { name: 'leadership', categories: [1] },
  { name: '3D Printing', categories: [5] },
  { name: 'Freelance Marketing', categories: [9] },
  { name: 'Econometrics', categories: [1] },
  { name: 'Business Angels', categories: [1] },
  { name: 'strategy', categories: [1] },
  { name: 'Program Management', categories: [1] },
  { name: 'Scientific Research', categories: [5] },
  { name: 'Internet & Communications', categories: [1] },
  { name: 'Twitter Marketing', categories: [9] },
  { name: 'Venture Financing', categories: [1] },
  { name: 'Organizational Behavior', categories: [1] },
  { name: 'C#', categories: [11] },
  { name: 'Print Design', categories: [4, 2] },
  { name: '3D Modeling & CAD', categories: [5] },
  { name: 'Symfony', categories: [13] },
  { name: 'Game', categories: [6, 2] },
  { name: 'Software Engineering', categories: [11] },
  { name: 'VBA', categories: [1, 5] },
  { name: 'Google+ Marketing', categories: [9, 15] },
  { name: 'Industrial Engineering', categories: [5] },
  { name: 'Customer Service', categories: [1] },
  { name: 'Linux', categories: [11] },
  { name: 'Digital Photography', categories: [2] },
  {
    name: 'Saas Marketing and sales automation',
    categories: [9]
  },
  { name: 'M&A', categories: [1] },
  { name: 'Algorithm Development', categories: [5, 11, 7] },
  { name: 'Brand Ambassador', categories: [1, 9] },
  { name: 'Photo Editing', categories: [2, 15] },
  { name: 'management', categories: [1] },
  { name: 'Artificial Intelligence', categories: [7, 5, 11] },
  { name: 'Business Software', categories: [15] },
  { name: 'Article Writing', categories: [14] },
  { name: 'start ups', categories: [1] },
  { name: 'Blogging', categories: [9] },
  { name: 'Web Analytics', categories: [8] },
  { name: 'Rapid Prototyping', categories: [4, 12, 1] },
  { name: 'Game Development', categories: [6] },
  { name: 'WordPress', categories: [13, 10] },
  { name: 'Git', categories: [11, 12, 13] },
  { name: 'German', categories: [8] },
  { name: 'Risk Management', categories: [1] },
  { name: 'Corporate Law', categories: [1] },
  { name: 'MongoDB', categories: [3] },
  { name: 'SEM', categories: [9] },
  { name: 'International Law', categories: [1] },
  { name: 'Video Editing', categories: [15] },
  { name: 'Cost Analysis', categories: [1] },
  { name: 'Auditing', categories: [1] },
  { name: 'Investment Banking', categories: [1] },
  { name: 'Android', categories: [10] },
  { name: 'Product Lifecycle Management', categories: [1] },
  { name: 'Music', categories: [2] },
  { name: 'Cloud Computing', categories: [7] },
  { name: 'Ruby', categories: [13] },
  { name: 'Software Development', categories: [11] },
  { name: 'Financial Engineering', categories: [1] },
  { name: 'Research', categories: [5] },
  { name: 'MySQL Programming', categories: [3, 13] },
  { name: 'Concept Design', categories: [4] },
  { name: 'Financial Statements', categories: [1] },
  { name: 'Statistics', categories: [5] },
  { name: 'Analytics', categories: [1, 9, 15] },
  { name: 'Biotechnology', categories: [5] },
  { name: 'Corporate Brand Identity', categories: [1, 4] },
  { name: 'Internet Marketing', categories: [9] },
  { name: 'Project Scheduling', categories: [1] },
  { name: 'Supply Chain Management', categories: [1] },
  { name: 'Event Planning', categories: [1] },
  { name: 'Music Composition', categories: [2] },
  { name: 'React.js', categories: [13, 10] },
  { name: 'Microsoft Word', categories: [1, 15] },
  { name: 'Mechanical Engineering', categories: [5] },
  { name: 'Human Resources', categories: [1] },
  { name: 'Mathematics', categories: [5] },
  { name: 'Budgeting & Forecasting', categories: [1] },
  { name: 'Online Advertising', categories: [9, 1] },
  { name: 'Business Law', categories: [1] },
  { name: 'Public Speaking', categories: [1] },
  { name: 'Financial Reporting', categories: [1] },
  { name: 'Data Science', categories: [7, 3] },
  { name: 'Big Data', categories: [7, 3] },
  { name: 'User Interface Design', categories: [12, 4] },
  { name: 'Contract Law', categories: [1] },
  { name: 'Economics', categories: [1] },
  { name: 'Public Relations', categories: [1] },
  { name: 'Affiliate Marketing', categories: [9] },
  { name: 'SQL', categories: [3] },
  { name: 'Google analytics', categories: [9, 15] },
  { name: 'Negotiation', categories: [1] },
  { name: 'Accounting & Control', categories: [1] },
  { name: 'Financial Forecasting', categories: [1] },
  {
    name: 'Social Network & Community Development',
    categories: [9]
  },
  { name: 'CRM', categories: [13, 1] },
  { name: 'Business', categories: [1] },
  { name: 'Account management', categories: [1] },
  { name: 'Adobe InDesign', categories: [4, 15, 12] },
  { name: 'Microsoft PowerPoint', categories: [1, 15] },
  { name: 'Project Finance', categories: [1] },
  { name: 'Fundraising', categories: [1] },
  { name: 'Sales and Marketing', categories: [9] },
  { name: 'Spanish', categories: [8] },
  { name: 'Accounting', categories: [1] },
  { name: 'Google adwords', categories: [9, 15] },
  { name: 'Social Networking', categories: [9, 1] },
  { name: 'Machine Learning', categories: [7] },
  { name: 'Operations Management', categories: [1] },
  { name: 'Ruby on Rails', categories: [13] },
  { name: 'Photography', categories: [2] },
  { name: 'Financial Management', categories: [1] },
  { name: 'Advertising', categories: [9, 1] },
  { name: 'Microsoft Office', categories: [1, 15] },
  { name: 'Direct Marketing', categories: [9, 1] },
  { name: 'Event Management', categories: [1] },
  { name: 'Advertising Strategy', categories: [1, 9] },
  { name: 'Adobe Illustrator', categories: [4, 12, 15] },
  { name: 'Ecommerce', categories: [1, 9] },
  { name: 'Data Analytics', categories: [1, 9] },
  { name: 'Web Design', categories: [12] },
  { name: 'Facebook Marketing', categories: [9] },
  { name: 'Market Research', categories: [1] },
  { name: 'Strategic Planning', categories: [1, 9] },
  { name: 'Growth Hacking', categories: [9, 1] },
  { name: 'Branding', categories: [4, 2] },
  { name: 'Project Planning', categories: [1] },
  { name: 'User Experience Design', categories: [12, 4] },
  { name: 'Lean Startup', categories: [1] },
  { name: 'Java', categories: [13, 11, 6] },
  { name: 'Email Marketing', categories: [9] },
  { name: 'C++', categories: [11, 6] },
  { name: 'French', categories: [8] },
  { name: 'Microsoft Excel', categories: [1, 15] },
  { name: 'Node.js', categories: [13, 10] },
  { name: 'Sales', categories: [1] },
  { name: 'Logo Design', categories: [4, 2] },
  { name: 'Consulting', categories: [1] },
  { name: 'English', categories: [8] },
  { name: 'Audio Production', categories: [2] },
  { name: 'Business Analysis', categories: [1] },
  { name: 'Business Plans', categories: [1] },
  { name: 'Python', categories: [11] },
  { name: 'Startups', categories: [1] },
  { name: 'Corporate Strategy', categories: [1] },
  { name: 'UX/UI Design', categories: [12, 4] },
  { name: 'Financial Analysis', categories: [1] },
  { name: 'Animation', categories: [6, 4] },
  { name: 'Social Media Marketing', categories: [9, 1] },
  { name: 'Fashion Design', categories: [4, 2] },
  { name: 'Robotics', categories: [5] },
  { name: 'Product Management', categories: [1] },
  { name: 'Computer Graphics', categories: [6, 5] },
  { name: 'Corporate Finance', categories: [1] },
  { name: 'Business Management', categories: [1] },
  { name: 'Electrical Engineering', categories: [5] },
  { name: 'iOS', categories: [13] },
  { name: 'Angular.js', categories: [13, 10] },
  { name: 'Illustration', categories: [2] },
  { name: 'Marketing Strategy', categories: [9, 1] },
  { name: 'Unix/Linux System Administrator', categories: [7] },
  { name: 'Business Development', categories: [1] },
  { name: 'Mobile Programming', categories: [10] },
  { name: 'Marketing', categories: [9, 1] },
  { name: 'Video Production', categories: [2] },
  { name: 'Digital Marketing', categories: [9, 1] },
  { name: 'Data Engineering', categories: [7, 5, 3] },
  { name: 'jQuery', categories: [13, 10] },
  { name: 'Strategy & Business Development', categories: [1] },
  { name: 'Project Management', categories: [1, 9] },
  { name: 'Computer Engineering', categories: [5, 11, 7] },
  { name: 'E-learning', categories: [1] },
  { name: 'Php', categories: [11, 12] },
  { name: 'SEO', categories: [7, 9, 1] },
  { name: 'GitHub', categories: [7, 11, 13] },
  { name: 'Lean', categories: [1] },
  { name: 'Venture Capital', categories: [1] },
  { name: 'Graphic Design', categories: [4, 12, 2] },
  { name: 'Social Networking Development', categories: [9, 1] },
  { name: 'Adobe Photoshop', categories: [2, 12, 4] },
  { name: 'Javascript', categories: [13, 12, 10] },
  { name: 'Web Development', categories: [13] },
  { name: 'CSS', categories: [13, 12, 10] },
  { name: 'Analytics', categories: [1] },
  { name: 'HTML', categories: [13, 12, 10] },
  { name: 'Product Design', categories: [4, 2] },
  { name: 'Communication', categories: [1, 9] },
  { name: 'Programming', categories: [11, 10] },
  { name: 'Entrepreneurship', categories: [1] }
];
