module.exports = 
 [ { name: 'Business' },
  { name: 'Creativity' },
  { name: 'Databases' },
  { name: 'Design' },
  { name: 'Manufacturing and Engineering' },
  { name: 'Game Development' },
  { name: 'IT' },
  { name: 'Languages' },
  { name: 'Sales & Marketing' },
  { name: 'Mobile Development' },
  { name: 'Software development' },
  { name: 'Web Design' },
  { name: 'Web Development' },
  { name: 'Writing' },
  { name: 'Tools' },
  { name: 'Random' } ]
